version: '3.4'


x-base: &base
  networks:
    - slackbotr
  restart: always
  logging:
    options:
      max-size: "10m"
      max-file: "10"


services:

  slackbotr:
    <<: *base
    image: "nsidc/slackbotr"
    volumes:
      - ./example_slackbots:/slackbots
