version: '3.4'


x-base: &base
  networks:
    - slackbotr
  restart: always
  logging:
    options:
      max-size: "1m"
      max-file: "1"


networks:
  slackbotr:


services:

  slackbotr:
    <<: *base
    image: "nsidc/slackbotr"
    volumes:
      - ./example_slackbots:/slackbots
